# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: v1/clock.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("v1/clock.proto", :syntax => :proto3) do
    add_message "resources.v1.Clock" do
      optional :timestamp, :int32, 1
    end
  end
end

module Resources
  module V1
    Clock = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("resources.v1.Clock").msgclass
  end
end
