# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: v1/search.proto for package 'resources.v1'

require 'grpc'
require 'v1/search_pb'

module Resources
  module V1
    module SearchService
      class Service

        include ::GRPC::GenericService

        self.marshal_class_method = :encode
        self.unmarshal_class_method = :decode
        self.service_name = 'resources.v1.SearchService'

        rpc :Search, ::Resources::V1::SearchRequest, ::Resources::V1::SearchResponse
      end

      Stub = Service.rpc_stub_class
    end
  end
end
