# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: v1/search.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("v1/search.proto", :syntax => :proto3) do
    add_message "resources.v1.SearchRequest" do
      optional :query, :string, 1
    end
    add_message "resources.v1.SearchResponse" do
      optional :result, :string, 1
    end
  end
end

module Resources
  module V1
    SearchRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("resources.v1.SearchRequest").msgclass
    SearchResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("resources.v1.SearchResponse").msgclass
  end
end
